auth:
  hash:
    cost: 32
  token:
    duration: 900 # in seconds
    rs512_key_pair_bit_size: 2048
database:
  host: "0.0.0.0"
  port: 3306
  username: "root"
  password: "secret"
  database: "idm"
log:
  level: "debug" # [debug, info, warn, error, panic]
cache:
  addr: "0.0.0.0:6379"
  username: ""
  password: ""
  db: 0