auth:
  hash:
    cost: 32
  token:
    duration: 86400 # in seconds
    rs512_key_pair_bit_size: 2048
database:
  type: "mysql"
  host: "0.0.0.0"
  port: 3306
  username: "root"
  password: "secret"
  database: "idm"
log:
  level: "debug" # [debug, info, warn, error, panic]
cache:
  type: "redis" # [redis, in-memory]
  addr: "0.0.0.0:6379"
  username: ""
  password: ""
  db: 0
grpc:
  address: "0.0.0.0:8080"
  get_download_task_file:
    response_buffer_size: 2kb
http:
  address: "0.0.0.0:8081"
  mode: "development" # [development, production]
mq:
  addresses: ["0.0.0.0:9092"]
  client_id: "1"
cron:
  execute_all_pending_download_task:
    schedule: "@every 1m"
    concurrency_limit: 8
  update_failed_download_task_status_to_pending:
    schedule: "@every 10m"
download:
  mode: "s3"
  download_directory: "./downloads/"
  bucket: "idm"
  address: "0.0.0.0:9000"
  username: "root"
  password: "secret123"
